In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from pandas import Series, DataFrame

In [ ]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 20
pd.options.display.max_columns = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)

# Pandas Data Structure


## Series

Create series using array

In [77]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [78]:
obj.array

<NumpyExtensionArray>
[4, 7, -5, 3]
Length: 4, dtype: int64

In [79]:
obj.index

RangeIndex(start=0, stop=4, step=1)

Create series using array and index

In [80]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [81]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [82]:
obj2["a"]

-5

In [83]:
obj2["d"] = 6

In [84]:
obj2[["c", "a", "d"]]

c    3
a   -5
d    6
dtype: int64

In [88]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [89]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [90]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [91]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [92]:
# check key exist
"b" in obj2

True

In [93]:

"e" in obj2

False

Use dict to create series

In [94]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [95]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [96]:
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

Check mission values

In [97]:
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [98]:

pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [99]:
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [100]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [101]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [102]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [103]:
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [104]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [105]:

obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

## DataFrame

Create DataFrame using dict

In [107]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
frame.head()

In [ ]:
frame.tail()

In [ ]:
pd.DataFrame(data, columns=["year", "state", "pop"])

In [109]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [110]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [111]:
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [112]:

frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [113]:
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [114]:

frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [115]:
frame2["debt"] = 16.5
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [116]:
frame2["debt"] = np.arange(6.)
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [117]:
val = pd.Series([-1.2, -1.5, -1.7], index=["two", "four", "five"])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [118]:

frame2["debt"] = val
frame2

   year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6   NaN
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9   NaN
5  2003  Nevada  3.2   NaN

In [119]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

   year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6   NaN     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9   NaN    False
5  2003  Nevada  3.2   NaN    False

In [120]:
del frame2["eastern"]
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [121]:
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

In [122]:
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [123]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [124]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

In [125]:
pdata = {"Ohio": frame3["Ohio"][:-1],
         "Nevada": frame3["Nevada"][:2]}
pd.DataFrame(pdata)

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [126]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [127]:
frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [128]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## Index Objects

In [131]:
obj = pd.Series(np.arange(3), index=["a", "b", "c"])
obj

a    0
b    1
c    2
dtype: int64

In [130]:

index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [132]:

index[1:]

Index(['b', 'c'], dtype='object')

In [133]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [134]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [135]:

obj2.index is labels

True

In [136]:
frame3

state  Ohio  Nevada
year
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [137]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [138]:
type(frame3.columns)

pandas.core.indexes.base.Index

In [139]:
"Ohio" in frame3.columns

True

In [140]:
2003 in frame3.index

False

In [141]:
list(frame3.index)

[2000, 2001, 2002]

In [142]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# Essential Functionality

## Reindexing

In [143]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [144]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [145]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [146]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [147]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=["a", "c", "d"],
                     columns=["Ohio", "Texas", "California"])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [148]:
frame2 = frame.reindex(index=["a", "b", "c", "d"])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [149]:
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [150]:
frame.reindex(states, axis="columns")

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [151]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

   California  Texas
a           2      1
d           8      7
c           5      4

## Dropping Entries from an Axis

In [152]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [153]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [154]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

### Drop axis from DataFrame

In [155]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [156]:
data.drop(index=["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [158]:
data.drop(columns=["two"])

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [159]:
data.drop("two", axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [160]:
data.drop(["two", "four"], axis="columns")

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

## Indexing, Selection, and Filtering

### Indexing

In [161]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [162]:

obj["b"]

1.0

In [163]:

obj[1]

<ipython-input-163-fbfcaec2cced>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]

1.0

In [164]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [165]:

obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [166]:

obj[[1, 3]]

<ipython-input-166-d1c6085fe620>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [168]:

obj[obj < 2]

a    0.0
b    1.0
dtype: float64

### Selection

Why `loc` is preferred

In [169]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [170]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])
obj1

2    1
0    2
1    3
dtype: int64

In [171]:
obj2 = pd.Series([1, 2, 3], index=["a", "b", "c"])
obj2

a    1
b    2
c    3
dtype: int64

In [172]:

obj1[[0, 1, 2]]

0    2
1    3
2    1
dtype: int64

In [173]:

obj2[[0, 1, 2]]

<ipython-input-173-6353957a2389>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj2[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [174]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [175]:
obj2.iloc[[0, 1, 2]]

a    1
b    2
c    3
dtype: int64

In [176]:
obj2.loc["b":"c"]

b    2
c    3
dtype: int64

In [177]:
obj2.loc["b":"c"] = 5
obj2

a    1
b    5
c    5
dtype: int64

In [178]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [179]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [180]:

data[["three", "one"]]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [181]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [182]:
data["three"] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [183]:

data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [184]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [185]:
type(data<5)

pandas.core.frame.DataFrame

In [186]:
data[data < 5] = 0
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection with `loc` and `iloc`

In [187]:
# Returns Series
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [188]:
# Returns DataFrame
data.loc[["Colorado"]]

          one  two  three  four
Colorado    0    5      6     7

In [189]:
data.loc[["Colorado", "New York"]]

          one  two  three  four
Colorado    0    5      6     7
New York   12   13     14    15

In [190]:
# returns Series
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [191]:
data.loc["Colorado"][["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [192]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [193]:
data.iloc[[2, 1]]

          one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [194]:

data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [195]:

data.iloc[[1, 2], [3, 0, 1]]

          four  one  two
Colorado     7    0    5
Utah        11    8    9

In [196]:
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [197]:

data.iloc[:, :3][data.three > 5]

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [198]:
data.loc[data.three >= 2]

          one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### integer indexing pitfalls

In [207]:
ser = pd.Series(np.arange(3.))
ser[-1]

KeyError: -1

In [208]:
ser2 = pd.Series(np.arange(3.), index=["a", "b", "c"])
ser2[-1]

<ipython-input-208-f39333d65c2b>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser2[-1]

2.0

In [209]:
ser.iloc[-1]

2.0

In [202]:
ser[:2]

0    0.0
1    1.0
dtype: float64

### Pitfalls with chained indexing

In [210]:
data.loc[:, "one"] = 1
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    3      3     3
Utah        1    5      5     5
New York    1    3      3     3

In [211]:

data.iloc[2] = 5
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    3      3     3
Utah        5    5      5     5
New York    1    3      3     3

In [212]:
data.loc[data["four"] > 1]

          one  two  three  four
Colorado    1    3      3     3
Utah        5    5      5     5
New York    1    3      3     3

In [213]:
data.loc[data["four"] > 5] = 3
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    3      3     3
Utah        5    5      5     5
New York    1    3      3     3

In [217]:
# Pitfall !!!
data.loc[data.three == 5]["three"] = 6

In [215]:
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    3      3     3
Utah        5    5      5     5
New York    1    3      3     3

In [216]:
data.loc[data.three == 5, "three"] = 6
data

          one  two  three  four
Ohio        1    0      0     0
Colorado    1    3      3     3
Utah        5    5      6     5
New York    1    3      3     3

## Arithmetic and Data Alignment

In [219]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [220]:

s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=["a", "c", "e", "f", "g"])
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [221]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [223]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [224]:

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])

df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [225]:
df1 + df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [226]:
df1 = pd.DataFrame({"A": [1, 2]})
df1

   A
0  1
1  2

In [227]:

df2 = pd.DataFrame({"B": [3, 4]})
df2

   B
0  3
1  4

In [229]:
df1 + df2

    A   B
0 NaN NaN
1 NaN NaN

### Arithmetic methods with fill values

In [230]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))
df1

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [231]:

df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))
df2.loc[1, "b"] = np.nan

df2

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [232]:
df1 + df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [233]:
df1.add(df2, fill_value=0)

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [235]:
1 / df1

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [236]:

df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [237]:
df1.reindex(columns=df2.columns, fill_value=0)

     a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

### Operations between DataFrame and Series

In [241]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [243]:

series = frame.iloc[0]

series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [244]:
frame - series

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [245]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])
series2

b    0
e    1
f    2
dtype: int64

In [246]:

frame + series2

          b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

**# Stoped here**

In [ ]:
series3 = frame["d"]
frame
series3
frame.sub(series3, axis="index")

In [ ]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])
frame
np.abs(frame)

In [ ]:
def f1(x):
    return x.max() - x.min()

frame.apply(f1)

In [ ]:
frame.apply(f1, axis="columns")

In [ ]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])
frame.apply(f2)

In [ ]:
def my_format(x):
    return f"{x:.2f}"

frame.applymap(my_format)

In [ ]:
frame["e"].map(my_format)

In [ ]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj
obj.sort_index()

In [ ]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=["three", "one"],
                     columns=["d", "a", "b", "c"])
frame
frame.sort_index()
frame.sort_index(axis="columns")

In [ ]:
frame.sort_index(axis="columns", ascending=False)

In [ ]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

In [ ]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

In [ ]:
obj.sort_values(na_position="first")

In [ ]:
frame = pd.DataFrame({"b": [4, 7, -3, 2], "a": [0, 1, 0, 1]})
frame
frame.sort_values("b")

In [ ]:
frame.sort_values(["a", "b"])

In [ ]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

In [ ]:
obj.rank(method="first")

In [ ]:
obj.rank(ascending=False)

In [ ]:
frame = pd.DataFrame({"b": [4.3, 7, -3, 2], "a": [0, 1, 0, 1],
                      "c": [-2, 5, 8, -2.5]})
frame
frame.rank(axis="columns")

In [ ]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj

In [ ]:
obj.index.is_unique

In [ ]:
obj["a"]
obj["c"]

In [ ]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),
                  index=["a", "a", "b", "b", "c"])
df
df.loc["b"]
df.loc["c"]

In [ ]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=["a", "b", "c", "d"],
                  columns=["one", "two"])
df

In [ ]:
df.sum()

In [ ]:
df.sum(axis="columns")

In [ ]:
df.sum(axis="index", skipna=False)
df.sum(axis="columns", skipna=False)

In [ ]:
df.mean(axis="columns")

In [ ]:
df.idxmax()

In [ ]:
df.cumsum()

In [ ]:
df.describe()

In [ ]:
obj = pd.Series(["a", "a", "b", "c"] * 4)
obj.describe()

In [ ]:
price = pd.read_pickle("examples/yahoo_price.pkl")
volume = pd.read_pickle("examples/yahoo_volume.pkl")

In [ ]:
returns = price.pct_change()
returns.tail()

In [ ]:
returns["MSFT"].corr(returns["IBM"])
returns["MSFT"].cov(returns["IBM"])

In [ ]:
returns.corr()
returns.cov()

In [ ]:
returns.corrwith(returns["IBM"])

In [ ]:
returns.corrwith(volume)

In [ ]:
obj = pd.Series(["c", "a", "d", "a", "a", "b", "b", "c", "c"])

In [ ]:
uniques = obj.unique()
uniques

In [ ]:
obj.value_counts()

In [ ]:
pd.value_counts(obj.to_numpy(), sort=False)

In [ ]:
obj
mask = obj.isin(["b", "c"])
mask
obj[mask]

In [ ]:
to_match = pd.Series(["c", "a", "b", "b", "c", "a"])
unique_vals = pd.Series(["c", "b", "a"])
indices = pd.Index(unique_vals).get_indexer(to_match)
indices

In [ ]:
data = pd.DataFrame({"Qu1": [1, 3, 4, 3, 4],
                     "Qu2": [2, 3, 1, 2, 3],
                     "Qu3": [1, 5, 2, 4, 4]})
data

In [ ]:
data["Qu1"].value_counts().sort_index()

In [ ]:
result = data.apply(pd.value_counts).fillna(0)
result

In [ ]:
data = pd.DataFrame({"a": [1, 1, 1, 2, 2], "b": [0, 0, 1, 0, 0]})
data
data.value_counts()

In [ ]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS

In [238]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [239]:
arr[0]

array([0., 1., 2., 3.])

In [240]:

arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])